name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Run IDs
        id: get-runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the ID of the latest successful run for the neoforge branch
          NEO_RUN_ID=$(gh run list --workflow build.yml --branch 1.21.1-neoforge --status success --limit 1 --json databaseId -q '.[0].databaseId')
#          # Fetch the ID for the fabric branch
#          FAB_RUN_ID=$(gh run list --workflow build.yml --branch 1.21.1-fabric --status success --limit 1 --json databaseId -q '.[0].databaseId')
          
          echo "neo_id=$NEO_RUN_ID" >> $GITHUB_OUTPUT
#          echo "fab_id=$FAB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Download NeoForge
        uses: actions/download-artifact@v4
        with:
          name: neoforge-artifact
          run-id: ${{ steps.get-runs.outputs.neo_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./dist/neoforge

#      - name: Download Fabric
#        uses: actions/download-artifact@v4
#        with:
#          name: fabric-artifact
#          run-id: ${{ steps.get-runs.outputs.fab_id }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path: ./dist/fabric

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          files: |
            ./dist/neoforge/*.jar
            ./dist/fabric/*.jar